# Generated by Django 3.0 on 2021-10-12 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=100)),
                ('noOfQuestions', models.IntegerField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('regdno', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('semail', models.EmailField(max_length=100)),
                ('spsw', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semail', models.EmailField(max_length=100)),
                ('marks_scored', models.IntegerField(default=0)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.ExamDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('opt1', models.CharField(max_length=100)),
                ('opt2', models.CharField(max_length=100)),
                ('opt3', models.CharField(max_length=100, null=True)),
                ('opt4', models.CharField(max_length=100, null=True)),
                ('ans', models.CharField(max_length=100)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.ExamDetails')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Faculty')),
            ],
        ),
    ]
