# Generated by Django 3.0 on 2021-10-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_examdetails_questions_studentregistration_studentsresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qmarks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentsresults',
            name='marks_scored',
            field=models.IntegerField(null=True),
        ),
    ]
